In [1]:
import numpy as np

In [8]:
lista=np.array([1,2,3,4,])

In [6]:
print(lista)

[1 2 3 4]


In [7]:
type(lista)

numpy.ndarray

In [6]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)

In [11]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
lista[3]+lista[2]

7

como tener toda la fila de una matriz

In [19]:
matriz[0]

array([1, 2, 3])

como tener un valor de una matriz

In [18]:
matriz[0,2]

3

como tener un rango de valores de un array?

In [20]:
lista[1:3]

array([2, 3])

In [22]:
lista[2:]

array([3, 4])

como tener un valor de una matriz?

In [7]:
matriz[1,1]

5

En cambio si no se le da una posción de End se regresan todos los elementos hasta el final del array.

In [9]:
lista1=np.array([1,1,2,1,5,54])

In [11]:
lista1[2:]

array([ 2,  1,  5, 54])

Como convertir los datos en string

In [12]:
lista1=lista1.astype(np.string_)

In [15]:
print(lista1)

[b'1' b'1' b'2' b'1' b'5' b'54']


como definir un tenzor

In [16]:
tensor=np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])

In [17]:
print(tensor)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


como definir 5 dimenciones con arrray

In [21]:
jugando=np.array([1,2,3],ndmin=5)

como definir 4 dimenciones

In [22]:
fourDim=np.array([1,2,3],ndmin=4)
fourDim

array([[[[1, 2, 3]]]])

In [2]:
ndim()

NameError: name 'ndim' is not defined

In [27]:
numeros= np.arange(1,125,5)
numeros

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121])

5. Coo crear matriz de puros 0 

In [30]:
numeros1=np.zeros(5)
numeros1

array([0., 0., 0., 0., 0.])

6. como reducir la dimencion de una matriz

In [32]:
lista2=np.squeeze(jugando)
lista2

array([1, 2, 3])

7. como crear un lista de puros 1

In [33]:
lista_de_unos=np.ones(5)

8. como  crear un matriz identidad ?

In [34]:
MatrizInd=np.eye(3)
MatrizInd

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
from random import random


total=np.full((random,6),3)
total

TypeError: 'builtin_function_or_method' object cannot be interpreted as an integer

como crear matriz de ceros

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

coomo crear una matriz de 1

In [6]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
#np.linspace(inicio,fin,cantida)
np.linspace(0,10,200)

array([ 0.        ,  0.05025126,  0.10050251,  0.15075377,  0.20100503,
        0.25125628,  0.30150754,  0.35175879,  0.40201005,  0.45226131,
        0.50251256,  0.55276382,  0.60301508,  0.65326633,  0.70351759,
        0.75376884,  0.8040201 ,  0.85427136,  0.90452261,  0.95477387,
        1.00502513,  1.05527638,  1.10552764,  1.15577889,  1.20603015,
        1.25628141,  1.30653266,  1.35678392,  1.40703518,  1.45728643,
        1.50753769,  1.55778894,  1.6080402 ,  1.65829146,  1.70854271,
        1.75879397,  1.80904523,  1.85929648,  1.90954774,  1.95979899,
        2.01005025,  2.06030151,  2.11055276,  2.16080402,  2.21105528,
        2.26130653,  2.31155779,  2.36180905,  2.4120603 ,  2.46231156,
        2.51256281,  2.56281407,  2.61306533,  2.66331658,  2.71356784,
        2.7638191 ,  2.81407035,  2.86432161,  2.91457286,  2.96482412,
        3.01507538,  3.06532663,  3.11557789,  3.16582915,  3.2160804 ,
        3.26633166,  3.31658291,  3.36683417,  3.41708543,  3.46

In [9]:
#np.eye(#)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#generaun valor aletorios totalmen
np.random.rand(4,2)

array([[0.75174935, 0.61663238],
       [0.24079186, 0.10402754],
       [0.01669268, 0.16472374],
       [0.54198344, 0.06687528]])

In [17]:
np.random.randint(1,3)

2

In [19]:
#permite tener datos aleatorios 
np.random.randint(1,100,[10,10])

array([[60, 42, 13, 82, 70, 25, 76, 30, 61, 42],
       [18, 73, 25, 75, 57, 97,  2, 35, 34, 63],
       [27, 48, 34, 41, 58, 92, 11, 27, 48, 97],
       [90, 86, 33, 42, 60, 69, 73,  1, 81, 45],
       [68, 87, 72, 50, 42, 26, 81, 25, 86,  4],
       [23, 34, 10, 32, 32, 73, 74, 34, 84, 36],
       [26, 32, 11, 52, 17, 77, 41, 48, 81, 36],
       [82, 52, 62, 87,  2, 67, 64, 43, 80, 54],
       [32, 68, 75, 90, 12, 83, 68, 21, 21, 35],
       [42, 36,  7, 65, 58, 42, 85, 44, 63, 63]])

## SHAPE Y RESHAPE

In [21]:
arr=np.random.randint(1,10,(3,2))
arr

array([[1, 2],
       [8, 7],
       [7, 9]])

In [23]:
arr.shape

(3, 2)

como cambiar la forma de los arreglos 3*2  a 2*3 

In [29]:
arr.reshape(1,6)

array([[1, 2, 8, 7, 7, 9]])

In [30]:
arr1=np.random.randint(2,25,(15,16))

In [45]:
np.reshape(arr1,(3,80),'C')

array([[ 2,  6, 16, 22, 24, 20, 22,  9, 15, 19, 17, 23, 20, 13, 10, 14,
         5,  5, 13, 17,  8, 10, 24,  9, 14, 20,  5,  5, 23, 12, 21, 20,
        13, 12, 12, 16, 14, 12, 22, 20, 20,  5, 10, 15, 16, 17,  9, 22,
        21,  8, 20, 12, 19,  2,  9, 20, 23,  6, 16,  4,  5, 12, 24, 17,
        13, 21, 23, 21, 24, 24, 18,  5, 14, 13, 16, 13, 10,  3, 16,  5],
       [ 6, 12, 11,  9,  5,  7, 13, 19, 19, 21,  5,  2,  6, 18, 20, 10,
        13,  3, 10,  7,  2,  7,  9,  8,  8, 19, 16, 19, 12,  2,  2, 10,
        18, 23,  4,  8, 15, 24,  2, 18, 18, 11, 23, 16,  7, 22, 19, 17,
        11,  5, 14,  3,  2,  2, 16,  7, 21, 20, 20,  4, 11,  5,  5, 13,
         8, 10, 15, 11, 16, 22,  8, 18, 20, 10, 19, 21, 23,  5, 14,  8],
       [15, 16,  8, 21, 12, 10,  9,  4, 20, 10,  4, 16, 20, 14,  6,  8,
        19,  6, 22, 21,  4,  7,  3, 10, 17, 20,  6, 16,  9,  2,  9, 18,
        20, 11,  5,  5, 20, 12, 11, 19, 24, 16,  7, 16, 24, 11, 15,  8,
        17, 21, 14, 18, 14,  7, 11, 11, 18,  2, 17,  2, 22, 18

## FUNCIONES PRINCIPALES

import 

In [46]:
import numpy as np

In [54]:
arr=np.random.randint(4,15,10)
arr

array([ 6,  9, 12, 11, 10,  6, 10, 10, 10,  4])

In [50]:
matriz1=np.reshape(arr,(2,5),'c')

In [51]:
matriz1

array([[ 7,  8, 12,  7,  4],
       [11, 13,  8, 13,  9]])

In [55]:
arr.max()

12

In [62]:
#como hacerlo solo por el eje 1
matriz1.max(0)

array([11, 13, 12, 13,  9])

In [63]:
arr1.argmax()

4

In [56]:
matriz1.min()

4

In [64]:
np.var(arr)

5.959999999999999

In [65]:
np.std(arr)

2.4413111231467406

In [66]:
np.mean(arr)

8.8

In [67]:
a = np.array([[1,2],[3,4]])

In [68]:
b=np.array([5,6])

In [69]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
b.ndim

2

In [72]:
np.concatenate((a,b.T),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

## COPY

- nos permite salvarnos de la herencia de pytho

In [73]:
arr2=np.arange(0,11)

In [76]:
trozoarr2=arr2[0:6]

In [78]:
trozoarr2[:]=0
trozoarr2

array([0, 0, 0, 0, 0, 0])

In [79]:
arr2

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [84]:
arr_copy=arr2.copy()

In [82]:
arr_copy[:]=100

In [85]:
arr2

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## CONDICIONES

- sirve para filtar info en data set

In [87]:
import numpy as jhon

In [91]:
jhon=jhon.linspace(1,10,10,dtype='int8')

In [93]:
indices=jhon>5

In [96]:
jhon[(jhon>5) & (arr<9)]=100

In [97]:
jhon

array([  1,   2,   3,   4,   5, 100,   7,   8,   9, 100], dtype=int8)

## Operaciones

In [99]:
import numpy as gia

In [98]:
lista=[1,2]

In [100]:
lista*2

[1, 2, 1, 2]

In [104]:
listaNum=np.random.randint(0,10,(10))

In [105]:
listaNum

array([6, 1, 0, 2, 2, 4, 3, 1, 8, 2])

In [106]:
listaNum*2

array([12,  2,  0,  4,  4,  8,  6,  2, 16,  4])

In [107]:
listaNum+5

array([11,  6,  5,  7,  7,  9,  8,  6, 13,  7])

In [109]:
1/(listaNum-6)

C:\Users\jhon.velasque\AppData\Local\Temp\ipykernel_9716\2989370252.py:1: RuntimeWarning: divide by zero encountered in divide
  1/(listaNum-6)


array([        inf, -0.2       , -0.16666667, -0.25      , -0.25      ,
       -0.5       , -0.33333333, -0.2       ,  0.5       , -0.25      ])

In [112]:
matriz1=listaNum.reshape(2,5)
matriz2=matriz1.copy()

In [113]:
matriz2+matriz1

array([[12,  2,  0,  4,  4],
       [ 8,  6,  2, 16,  4]])

In [114]:
np.matmul(matriz1,matriz2.T)

array([[45, 47],
       [47, 94]])

In [115]:
matriz1 @ matriz2.T

array([[45, 47],
       [47, 94]])

## aprendiendo mas

In [116]:
import numpy as np
import cv2
import matplotlib

ModuleNotFoundError: No module named 'cv2'