In [3]:
import numpy as np

In [5]:
lista=np.array([1,2,3,4,])

In [6]:
print(lista)

[1 2 3 4]


In [7]:
type(lista)

numpy.ndarray

In [10]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)

In [11]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
lista[3]+lista[2]

7

como tener toda la fila de una matriz

In [19]:
matriz[0]

array([1, 2, 3])

como tener un valor de una matriz

In [18]:
matriz[0,2]

3

como tener un rango de valores de un array?

In [20]:
lista[1:3]

array([2, 3])

In [22]:
lista[2:]

array([3, 4])